name = "workflow-live"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
account_id = "bfcb6ac5b3ceaf42a09607f6f7925823"

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "workflow-live"
binding = "WORKFLOW_LIVE"
class_name = "WorkFlowLive"

[[durable_objects.bindings]]
name = "WEBSOCKET_DO"
class_name = "WebSocketDO"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketDO"]

[assets]
directory = "src/static"
