name = "ai-collaboration-worker"
main = "src/index.ts"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
# account_id = "bfcb6ac5b3ceaf42a09607f6f7925823"

[observability]
enabled = true
head_sampling_rate = 1

[[workflows]]
name = "workflow-live"
binding = "WORKFLOW_LIVE"
class_name = "WorkFlowLive"

[[durable_objects.bindings]]
name = "WEBSOCKET_DO"
class_name = "WebSocketDO"

[[durable_objects.bindings]]
name = "PROJECT_COORDINATOR"
class_name = "ProjectCoordinator"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketDO"]

[[migrations]]
tag = "v2"
new_classes = ["ProjectCoordinator"]

[[d1_databases]]
binding = "AI_COLLABORATION_DB"
database_name = "ai-collaboration-db"
database_id = "ai-collaboration-db"

[assets]
directory = "src/static"
